-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: f233e2fc6f80727342134edc5cc6fecdbb1bffce
    hooks:
    -   id: flake8
        args: []
        additional_dependencies:
        - pep8-naming
