dist: trusty
before_install:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get install hfst python3-libhfst libhfst48-dev
    - cat /var/lib/dpkg/info/python3-libhfst.list
before_script:
      # https://stackoverflow.com/questions/25756134/how-to-add-my-module-to-travis-ci-pythonpath
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages/
script:
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages/
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - cat test/test-suite.log
notifications:
    irc:
        channels:
            - "chat.freenode.net#omorfi"
        on_failure: always
        on_success: always

